---

- name: 'create temporary workspace directory'
  tempfile:
    state: 'directory'
    suffix: '.{{ project_id }}'
  register: r_workspace

- set_fact:
    workspace_path: '{{ r_workspace.path }}'

- name: 'eks-specific setup'
  when: use_eks | default(false) | bool
  block:
    # it can happen that when initializing the workspace the EKS cluster has not been created, so ignore errors
    - name: 'update kubeconfig'
      command: aws --region {{ aws_region }} eks update-kubeconfig --name {{ env }}-{{ project_id }}-eks
      ignore_errors: true
      when: env != 'ops'
    - name: 'protect Kubernetes configuration file'
      file:
        path: ~/.kube/config
        mode: '0600'
      ignore_errors: true
      when: env != 'ops'
