---

- name: 'check the common variables'
  include_tasks: '{{ role_path }}/../../tasks/validate-common-vars.yml'

- name: 'delete temporary workspace directory'
  file:
    path: '{{ workspace_path }}'
    state: 'absent'
  when: workspace_path is defined

- name: 'delete temporary files created with hard-coded path'
  file:
    path: '{{ item }}'
    state: 'absent'
  loop:
    - '/tmp/github_ci_repositories.json'
