---
# https://{listener_hostname}:8871, the listener_hostname can be found at https://docs.logz.io/user-guide/accounts/account-region.html
logzio_region: 'eu'

# Log message format, can be "json" or "text". If json, the lambda function will attempt to parse the message field as JSON and populate
# the event data with the parsed fields
logzio_format: 'json'

# Log message type. Valid value can be found at https://docs.logz.io/user-guide/log-shipping/built-in-log-types.html
# NOTE-zw: the document is a bit outdated, as the official default `logzio_cloudwatch_lambda` is not in the doc
logzio_type: 'logzio_cloudwatch_lambda'

# Compress data before sending to logz.io, can be "true" or "false" (string). If true, the Lambda will send compressed logs. If false,
# the Lambda will send uncompressed logs.
logzio_compress: 'true'

# Send all messages to logz.io, can be "true" or "false" (string). If false, we do not send logs of type START, END, REPORT.
# Choose true to send all log types.
logzio_send_all: 'false'

logzio_token_ssm_parameter_name: ''

# Will only be used to create log group that does not exist
default_log_group_retention_in_days: 3

# The location of the official shipper lambda code by logz.io.
# Check out https://github.com/logzio/logzio_aws_serverless/blob/master/python3/cloudwatch/sam-template.yaml for updates
logzio_shipper_lambda_code_s3_bucket: 'logzio-aws-integrations-eu-central-1'
logzio_shipper_lambda_code_s3_key: 'cloudwatch-auto-deployment/0.0.2/logzio-cloudwatch.zip'

