---
- name: '[logzio-shipper] format the type code'
  set_fact:
    logzio_type_kebab_case: "{{ logzio_type | lower | replace('_', '-') | replace('-logzio', '') | replace('logzio-', '')}}"

- name: '[logzio-shipper] assemble the lambda function bane'
  set_fact:
    # this is complex name: for different log type we need different lambda function, so does the different data shipping token, therefore we put these variables in the name
    logzio_lambda_name: "{{ env }}-{{ project_id }}-logzio-{{ logzio_format }}-{{ logzio_type_kebab_case }}-{{ ssmkey_logzio_token | hash('md5') | truncate(8, True, '') }}"

- name: '[logzio-shipper] set cloudformation template'
  set_fact:
    cloudformation_template: '{{ role_path }}/files/cf-logz.yml'

- name: '[logzio-shipper] deploy the logz.io logs'
  include_role:
    name: 'ringier.aws_cicd.run_cloudformation'
  vars:
    stack_name: '{{ logzio_lambda_name }}'
    template: '{{ cloudformation_template }}'
    repo_tag_override: 'ops-ci-aws'
    version_tag_override: 'v2.2.0'
