---

# ------------------
# Software component name, for the time being, valid values can be `crawler` or `processor`
software_component: ''

# ------------------
# DNS domain name
base_domain: ''

# ------------------
# IP Prefix List of the VPN network(s)
vpn_prefix_list_id_ipv4: ''

# ------------------
# Local VPC
local_vpc_cidr: ''

# -------------------------------
# RDS DB FQDN
rds_route53_record_name: '{{ software_component }}-db.{{ base_domain }}'
rds_route53_ro_record_name: '{{ software_component }}-db-ro.{{ base_domain }}'

# -------------------------------
# RDS DB
rds_db_name: '{{ project_id }}'
rds_schema_name: '{{ rds_db_name }}'
rds_port: '5432'
rds_instance_class: 'db.t3.medium'
rds_instances_amount: 1

# ------------------
# "root" of the database
ssmkey_rds_master_username_key: '/{{ project_id }}/{{ software_component }}/rds/master-username'
ssmkey_rds_master_password_key: '/{{ project_id }}/{{ software_component }}/rds/master-password'

# -------------------------------
# Generic readonly user's name
readonly_user_name: '{{ project_id }}_{{ software_component }}_readonly'
ssmkey_rds_readonly_password_key: '/{{ project_id }}/{{ software_component }}/rds/readonly-password'
ssmkey_rds_readonly_username_key: '/{{ project_id }}/{{ software_component }}/rds/readonly-username'
